apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-grpc-microservice-boilerplate
  annotations:
    github.com/project-slug: idkashutosh/go-grpc-microservice-boilerplate
spec:
  type: other
  lifecycle: unknown
  owner: Ashutosh
